ingress:
  rules:
    - component:
        name: videochat
      match:
        path:
          prefix: /
name: birdseed-staging
region: nyc
services:
  - github:
      branch: feature/digital_ocean
      repo: Responcierge/videochat
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: videochat
    source_dir: /
workers:
  - environment_slug: ruby-on-rails
    github:
      branch: main
      deploy_on_push: true
      repo: Responcierge/docker-cron
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: videochatcron
    source_dir: /
